# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: myapp-ingress
#   namespace: myapp
#   labels:
#     app: myapp
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: demo.sinovuyo.me
#     http:
#       paths:
#       - backend:
#           service:
#             name: myapp-service
#             port:
#               number: 80
#         path: /
#         pathType: Prefix
